language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev qt5-default build-essential
  wget
- wget http://developer.x-plane.com/wp-content/plugins/code-sample-generation/sample_templates/XPSDK300.zip
- unzip *.zip
- mv SDK XPlaneSDK
- qmake
script: make
branches:
  only:
  - master
notifications:
  recipients:
  - ville.ranki@iki.fi
  - dan.krusi@nerves.ch
  email:
    on_success: change
    on_failure: always
before_deploy:
- pushd extplane-plugin
- zip -r extplane.zip extplane
- popd
deploy:
  provider: releases
  api_key:
    secure: mGPELl1Bc2nkK6JPsyorKkYC7uAwP4H5AfGev5vpIoOfC0Kp/ubRNVKE3771/tzPw4P2QpYDTvl9dL0hGJcoVEUeomRuBoNViueAzpZVJQSNo68lbse+SAMi2JHSs+p0uyDdIVY51Hu5NFQYnDWvxIgbv4RF8mztymdSS1CtDlU=
  file: extplane-plugin/extplane.zip
  on:
    repo: vranki/ExtPlane

